# Generated by Django 5.0.1 on 2024-02-10 20:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 17, 36, 4, 978689), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 17, 36, 4, 978689))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
