  version: '3.5'
  services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - db
      restart: unless-stopped

    redis:
      image: redis:7.0-alpine
      ports:
        - '6379:6379'
      volumes:
        - redis:/data

  networks:
    db:
      driver: bridge

  volumes:
    db:
    redis: